name: Workflow name

# on: 
#   push:
#     branches:
#       - master
#   workflow_dispatch:

jobs:
  job-id:
    permissions:
      contents: read 
      id-token: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4    

    - uses: 'google-github-actions/auth@v2' 
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
        service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

    - run: gcloud auth login --cred-file="$GOOGLE_APPLICATION_CREDENTIALS"

    - run: sh scripts/interact_with_gcp_resources.sh